-- Data Analysis for Customer Cluster View of Minct Classics company
-- customer cluster view contain data from customers, orders, payments, employees tables

-- 1. Total customers for Mint classics company
select count(distinct customerNumber)
 from customers_cluster_view; 
 -- Ans: Total number of customer is 122
 
 -- 2. No of customers with orders
 select
 count(distinct customerNumber)
 from customers_cluster_view
 where orderNumber is not null; 
 -- Ans:98 members are with active ordering customers
 
 -- 3. finding out the top 10 high payment customers
 select customerNumber, customerName,
 sum(distinct paid_amount) as totalPaid
 from customers_cluster_view
 group by customerNumber, customerName
 order by totalPaid desc
 limit 10;
 -- Ans: Customer 'Euro+ Shopping Channel' has highest total payment amount ($71,538)
 
 -- 4. finding out the top 10 low payment customers
 select customerNumber, customerName,
 sum(distinct paid_amount) as totalPaid
 from customers_cluster_view
 where paid_amount <> 0
 group by customerNumber, customerName
 order by totalPaid asc
 limit 10;
 -- Ans: Customer Boards & Toys Company has lowest payment order ($7918)
 
 -- 5. counting orders per customers (for completed orders)
 select customerName,
 count(distinct orderNumber) as totalOrders
 from customers_cluster_view
 where Status in ('Shipped','Resolved','Disputed')
 group by customerName
 order by totalOrders desc;
 -- Ans: -- Ans: Customer 'Euro+ Shopping Channel' has highest orders (24 No)
 
 -- 6. customer acquired and retained year over year
 -- a. findingout the customers in each year
with customers_2003 as (
select
 Year(orderDate) as Year,
 count(distinct customerNumber) as new_customers
 from customers_cluster_view
 where Year(orderDate) = 2003
 group by Year
 ),
 newcustomers_2004 as (
 select
 Year(orderDate) as Year,
 count(distinct customerNumber) as new_customers
 from customers_cluster_view
 where Year(orderDate) = 2004 
and customerNumber not in (select customerNumber from customers_cluster_view where Year(orderDate) in (2003))
group by Year
),
newcustomers_2005 as (
select
 Year(orderDate) as Year,
 count(distinct customerNumber) as new_customers
 from customers_cluster_view
 where Year(orderDate) = 2005 
and customerNumber not in (select customerNumber from customers_cluster_view where Year(orderDate) in (2003, 2004))
group by Year
),
retained_2004 as (
select count(distinct customerNumber) As retained_customers
from customers_cluster_view
where Year(orderDate) = 2004 
and customerNumber in (select distinct customerNumber from customers_cluster_view where year(orderDate) = 2003)
),
retained_2005 as (
select count(distinct customerNumber) As retained_customers
from customers_cluster_view
where Year(orderDate) = 2005 
and customerNumber in (select customerNumber from customers_cluster_view where year(orderDate) in (2003, 2004))
)
SELECT 
    2003 AS year, new_customers, 0 AS retained_customers FROM customers_2003
UNION all
SELECT 
    2004 AS year, new_customers, retained_customers FROM newcustomers_2004, retained_2004
UNION all
SELECT 
	2005 AS year, new_customers, retained_customers FROM newcustomers_2005, retained_2005
ORDER BY year DESC;


-- 7. finding out total pyaments from each country
select 
country,
sum(distinct paid_amount) as total_amount
from customers_cluster_view
group by country
order by 2 asc;
-- contry USA highest total payments followed by UK, Switzerland

-- 8.finding out customers from each country
select 
country, count(distinct customerNumber) as customerCount
from customers_cluster_view
group by country
order by 2 desc;
-- Country USA has more customers followed by Germany and France



-- 9. quartileing the custtomer credit limit and comapring with total payemts
with creditquartile as (
select
customerNumber,
customerName,
creditLimit,
paid_amount as totalPayment,
ntile(4) over (order by creditLimit) as creditquartile
from customers_cluster_view
group by customerNumber, customerName, creditLimit, totalPayment
)
select 
	case 
		when creditquartile = 1 then 'low credit limit (1 quartile)'
		when creditquartile = 2 then 'moderate credit limit (2 quartile)'
		when creditquartile = 3 then 'high credit limit (3 quartile)'
		else 'premium credit (4 quartile)'
		end as creditCategory,
	sum(distinct totalPayment) as totalPayment
from creditquartile
group by creditCategory
order by 2 desc;

-- most of the payments were done by customers with high credit limits
-- this indicates that with increasing credit limit, customers are interested to buy more from the company.


-- 10. Calculatig total revenue generated by mint classics
select sum(distinct paid_amount) as revenue from customers_cluster_view;
-- Ans: total revenue generated by mint classics - $ 88,53,839.23'

-- 11. finding out the total sales made by each employee
select 
distinct salesRepEmployeeNumber as EmployeeNumber,
concat(firstName,' ',lastName) as EmployeeName,
sum(distinct paid_amount) as total_sales
from customers_cluster_view
where salesRepEmployeeNumber is not null
group by EmployeeNumber
order by 3 desc;

-- Ans: a. Employees 'Gerard Hernandez' and 'Leslie Jennings' made highest sales ($ '1112003.81' and $ '989906.55')
-- b. Employee 'Leslie Thompson' made lowest sales ($ '347533.03')

-- 12. 
-- A. Finding out the avearge delivery time (Days)
select
avg(coalesce(datediff(shippedDate, orderDate),0)) as days_for_shipping
from customers_cluster_view
where orderNumber is not null;

-- The average time a delivery is taking is 3.7 Days

-- B. finding out the average time for shippping after ordering by customer and categorise the delivery
select
customerName,
count(distinct orderNumber) as orders,
coalesce(datediff(shippedDate, orderDate),0) as days_for_shipping,
case 
when coalesce(datediff(shippedDate, orderDate),0) = 0 then 'On the Day Deliver'
when coalesce(datediff(shippedDate, orderDate),0) between 1 and 3 then 'Express Deliver'
when coalesce(datediff(shippedDate, orderDate),0) between 4 and 7 then 'Regular Delivery'
else 'Late Delivery'
end as Delivery_Type
from customers_cluster_view
where orderNumber is not null
group by 1,3,4
order by 3 desc;

-- Ans: The delivery date were ranged between 0 (same day as orderd) and 65 days (late deliveries)


-- 13. finding out the year wise order traffic for the company
select
Year(orderDate) as Year,
count(distinct orderNumber) as Orders
from customers_cluster_view
where orderNumber is not null and status in ('Shipped','Resolved','Disputed')
group by year
order by 2 desc;

-- Ans: a. year 2004 received more orders (146), followed by 2003 (109) and least were recieved during year 2005 (55)

-- 14. order status distribution across year, month and date
select
Year(orderDate) as Year,
Month(orderDate) as Month,
status,
count(distinct OrderNumber) as orders
from customers_cluster_view
group by Year, Month, status
order by Year desc, Month desc, status;

-- Ans: a. in 2003 and 2004 most of the orderes were received duirng year end 11 month.
-- b. in year 2005 most of the orders were received during 5 month.

-- 15. payment distribution over year and month for the company
select
Year(OrderDate) as Year,
Month(OrderDate) as Month,
sum(distinct paid_amount) as total_payment
from customers_cluster_view
group by 1, 2
order by year desc, month desc;

-- Ans: a. Highest payments were in year endings of 2003 and 2004 sugesting that holiday seasons are best for sales